version: '3'
services:
  api:
    build: .  # 指定Dockerfile所在目录
    ports:
      - "8088:8080"  
      - "8880:8080"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  redis:
    image: redis  # 使用官方的Redis镜像